import { useEffect, useRef, useState } from 'react'
import type { BoxCoords, CoverImage } from '../../types/card'
import { generateCoverImage, uploadCoverImage } from '../../lib/imageGen'
import { DEFAULT_IMAGE_MODEL, IMAGE_MODELS } from '../../lib/imageModels'
import { DEFAULT_TEXT_MODEL, TEXT_MODELS } from '../../lib/textModels'
import { DEFAULT_IMAGE_STYLE, IMAGE_STYLES } from '../../lib/imageStyles'
import { loadGenerationSettings, saveGenerationSettings } from '../../lib/generationSettings'

interface ImageLayerProps {
  box: BoxCoords
  coverImage: CoverImage | null
  onChange: (coverImage: CoverImage | null) => void
  genPrompt: { title: string; typeLine: string; rulesText: string; flavorText: string }
  autoGenerate?: boolean
}

export function ImageLayer({ box, coverImage, onChange, genPrompt, autoGenerate }: ImageLayerProps) {
  const fileInputRef = useRef<HTMLInputElement>(null)
  const [generating, setGenerating] = useState(false)
  const [uploading, setUploading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [showUrlInput, setShowUrlInput] = useState(false)
  const [urlValue, setUrlValue] = useState('')
  const [showModelSettings, setShowModelSettings] = useState(false)
  const [imageModel, setImageModel] = useState(DEFAULT_IMAGE_MODEL)
  const [textModel, setTextModel] = useState(DEFAULT_TEXT_MODEL)
  const [style, setStyle] = useState(DEFAULT_IMAGE_STYLE)
  const hasAutoGenerated = useRef(false)

  function handleFileChange(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0]
    if (!file) return
    e.target.value = ''
    const reader = new FileReader()
    reader.onload = async () => {
      setUploading(true)
      setError(null)
      try {
        const url = await uploadCoverImage(reader.result as string)
        onChange({
          source: 'upload',
          dataUrl: url,
          offsetXPct: 50,
          offsetYPct: 50,
          scale: 1,
        })
      } catch (err) {
        setError(err instanceof Error ? err.message : 'Failed to upload image')
      } finally {
        setUploading(false)
      }
    }
    reader.readAsDataURL(file)
  }

  function handleUrlSubmit() {
    const url = urlValue.trim()
    if (!url) return
    onChange({
      source: 'url',
      dataUrl: url,
      offsetXPct: 50,
      offsetYPct: 50,
      scale: 1,
    })
    setUrlValue('')
    setShowUrlInput(false)
  }

  async function handleGenerate() {
    setGenerating(true)
    setError(null)
    try {
      const dataUrl = await generateCoverImage({ ...genPrompt, imageModel, textModel, style })
      onChange({ source: 'generated', dataUrl, offsetXPct: 50, offsetYPct: 50, scale: 1 })
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to generate image')
    } finally {
      setGenerating(false)
    }
  }

  useEffect(() => {
    if (autoGenerate && !hasAutoGenerated.current && !coverImage) {
      hasAutoGenerated.current = true
      handleGenerate()
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [autoGenerate])

  useEffect(() => {
    const settings = loadGenerationSettings()
    setImageModel(settings.imageModel)
    setTextModel(settings.textModel)
    setStyle(settings.style)
  }, [])

  useEffect(() => {
    saveGenerationSettings({ imageModel, textModel, style })
  }, [imageModel, textModel, style])

  return (
    <div
      className="image-layer"
      style={{
        position: 'absolute',
        left: `${box.xPct}%`,
        top: `${box.yPct}%`,
        width: `${box.widthPct}%`,
        height: `${box.heightPct}%`,
      }}
    >
      {coverImage ? (
        <img
          src={coverImage.dataUrl}
          alt="Cover art"
          style={{
            width: '100%',
            height: '100%',
            objectFit: 'cover',
            objectPosition: `${coverImage.offsetXPct}% ${coverImage.offsetYPct}%`,
          }}
        />
      ) : (
        <div className="image-layer-empty">No cover image</div>
      )}

      {(generating || uploading) && (
        <div className="image-layer-loading">
          <div className="spinner" />
          <span>{generating ? 'Generating image…' : 'Uploading image…'}</span>
        </div>
      )}

      <button
        type="button"
        className="btn-overlay btn-icon image-layer-settings-btn"
        onClick={() => setShowModelSettings(true)}
        title="Model settings"
        aria-label="Model settings"
      >
        ⚙
      </button>

      <div className="image-layer-controls">
        <input
          ref={fileInputRef}
          type="file"
          accept="image/*"
          onChange={handleFileChange}
          style={{ display: 'none' }}
        />
        <button
          type="button"
          className="btn-overlay"
          onClick={() => fileInputRef.current?.click()}
          disabled={uploading}
        >
          {uploading ? 'Uploading…' : 'Upload'}
        </button>
        <button type="button" className="btn-overlay" onClick={handleGenerate} disabled={generating}>
          {generating ? 'Generating…' : 'Generate'}
        </button>
        <button type="button" className="btn-overlay" onClick={() => setShowUrlInput((v) => !v)}>
          URL
        </button>
        {coverImage && (
          <button type="button" className="btn-overlay" onClick={() => onChange(null)}>
            Clear
          </button>
        )}
      </div>
      {showUrlInput && (
        <div className="image-layer-url-input">
          <input
            type="text"
            placeholder="https://example.com/image.png"
            value={urlValue}
            onChange={(e) => setUrlValue(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === 'Enter') handleUrlSubmit()
            }}
          />
          <button type="button" className="btn-overlay" onClick={handleUrlSubmit}>
            Use
          </button>
        </div>
      )}
      {error && <div className="image-layer-error">{error}</div>}
      {showModelSettings && (
        <div className="model-settings-overlay" onClick={() => setShowModelSettings(false)}>
          <div className="model-settings-panel" onClick={(e) => e.stopPropagation()}>
            <div className="model-settings-header">
              <h3>Generation models</h3>
              <button type="button" className="btn btn-sm" onClick={() => setShowModelSettings(false)}>
                Close
              </button>
            </div>
            <label className="model-settings-field">
              Image model
              <select value={imageModel} onChange={(e) => setImageModel(e.target.value)}>
                {IMAGE_MODELS.map((model) => (
                  <option key={model.id} value={model.id}>
                    {model.label}
                  </option>
                ))}
              </select>
            </label>
            <label className="model-settings-field">
              Text model
              <select value={textModel} onChange={(e) => setTextModel(e.target.value)}>
                {TEXT_MODELS.map((model) => (
                  <option key={model.id} value={model.id}>
                    {model.label}
                  </option>
                ))}
              </select>
            </label>
            <label className="model-settings-field">
              Style
              <select value={style} onChange={(e) => setStyle(e.target.value)}>
                {IMAGE_STYLES.map((s) => (
                  <option key={s.id} value={s.id}>
                    {s.label}
                  </option>
                ))}
              </select>
            </label>
          </div>
        </div>
      )}
    </div>
  )
}
